name: Build and Unit Test .NET Project
on:
  workflow_call:
    inputs:
        USER_NAME:
            description: 'Username for private NuGet feed'
            required: true
            type: string
        ARTIFACT_RETENTION_DAYS:
            description: 'Number of days to retain build artifacts'
            required: false
            type: number
            default: 1
        WORKING_DIRECTORY:
            description: 'Working directory for the build process'
            required: false
            type: string
            default: '/'
        DOTNET_VERSION:
            description: 'List of .NET versions to build against'
            required: true
            type: string
        SOLUTION_RELATIVE_PATH:
            description: 'The file name of the solution'
            required: true
            type: string
jobs:
    build:
      uses: adaptive-network/.github/.github/workflows/build_dotnet.yml@release
      with:
        user_name: ${{ inputs.USER_NAME }}
        artifact_retention_days: ${{ inputs.ARTIFACT_RETENTION_DAYS }}
        working_directory: ${{ inputs.WORKING_DIRECTORY }}
        dotnet_version: ${{ inputs.DOTNET_VERSION }}
      secrets: inherit
    unit_tests:
        uses: adaptive-network/.github/.github/workflows/unit_test_dotnet.yml@release
        needs: build
        with:
          user_name: ${{ inputs.USER_NAME }}
          artifact_retention_days: ${{ inputs.ARTIFACT_RETENTION_DAYS }}
          working_directory: ${{ inputs.WORKING_DIRECTORY }}
          dotnet_version: ${{ inputs.DOTNET_VERSION }}
          solution_relative_path: ${{inputs.SOLUTION_RELATIVE_PATH}}
        secrets: inherit
