name: Run integration tests
on:
  workflow_call:
    inputs:
        USER_NAME:
            description: 'Username for private NuGet feed'
            required: true
            type: string
        ARTIFACT_RETENTION_DAYS:
            description: 'Number of days to retain build artifacts'
            required: false
            type: number
            default: 1
        WORKING_DIRECTORY:
            description: 'Working directory for the build process'
            required: false
            type: string
            default: '/'
        DOTNET_VERSION:
            description: 'List of .NET versions to build against'
            required: true
            type: string
        SOLUTION_RELATIVE_PATH:
            description: 'The solution file path'
            required: true
            type: string
jobs:
  integration_tests:
    runs-on: ubuntu-latest # Docker works better on Linux runners
    name: Run integration tests

    services:
      docker:
        image: docker:latest # Docker version
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: Add GitHub NuGet Source
        run: |
          echo Adding NuGet Source
          dotnet nuget add source --username ${{inputs.USER_NAME}} --password ${{ secrets.PACKAGE_MANAGER_TOKEN }} --store-password-in-clear-text --name github ${{vars.PRIVATE_NUGET_FEED}}
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
      - name: Restore dependencies
        run: dotnet restore ${{inputs.SOLUTION_RELATIVE_PATH}}
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests
        run: dotnet test ${{inputs.SOLUTION_RELATIVE_PATH}} --filter TestCategory=Integration --no-restore
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
